"""empty message

Revision ID: be5280d6884b
Revises: 9f55274ad2f1
Create Date: 2023-05-10 15:06:04.335447

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'be5280d6884b'
down_revision = '9f55274ad2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


    if environment == "production":
        op.execute(f"ALTER TABLE likes SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
